### ISSUE TITLE
Doesn't seem to work on localizable strings

### ISSUE THREAD

**Issue by nicholaslie90** [roana0229/android-xml-sorter#5]
Hi @roana0229, I'd like to thank you for your time to make this awesome plugin. However, upon my testing, it doesn't seem to work on localizable strings (strings-in.xml, strings-de.xml, etc) and only works on strings.xml. When I try to reformat the file, I got the following error.

<img width="1552" alt="screen shot 2016-11-25 at 16 21 03" src="https://cloud.githubusercontent.com/assets/4620070/20620229/4022f4c8-b32b-11e6-81f9-f8469c7b1d9a.png">

Here's the stacktrace:
`null
java.lang.NullPointerException
	at XmlSorterAction$NodeComparator.compare(XmlSorterAction.java:129)
	at XmlSorterAction$NodeComparator.compare(XmlSorterAction.java:119)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at XmlSorterAction.actionPerformed(XmlSorterAction.java:70)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by nicholaslie90** [comment]
Oh man, it turns out I got a malformed XML. Everything's good!

**Comment by roana0229** [comment]
Hi @nicholaslie90, Thank you for using this plugin!
